"use client"

import { FormEvent, useMemo, useState } from "react"
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"
import { ArrowRight, BadgeCheck, Boxes, Check, ChevronRight, CircleDollarSign, CloudUpload, Heart, Leaf, MapPin, PackageOpen, Search, Send, ShieldCheck, Sparkles, X, Zap } from "lucide-react"
import { Toaster, toast } from "sonner"

type Material = { id:number; name:string; category:string; quantity:string; location:string; price:string; carbon:string; owner:string; condition:string; color:string; icon:string; applications:string[] }
const materials: Material[] = [
 {id:1,name:"Recycled steel billets",category:"Metals",quantity:"24 tonnes",location:"Pune, MH",price:"₹42,000 / t",carbon:"38.4 t CO₂e",owner:"Apex Foundry",condition:"Verified grade",color:"steel",icon:"Fe",applications:["Structural members", "Fabrication feedstock", "Low-carbon infrastructure"]},
 {id:2,name:"Sorted aluminium scrap",category:"Metals",quantity:"8.5 tonnes",location:"Ahmedabad, GJ",price:"₹138,000 / t",carbon:"76.5 t CO₂e",owner:"NexCycle Works",condition:"Clean, baled",color:"aluminium",icon:"Al",applications:["Secondary smelting", "Extrusion billets", "Cast components"]},
 {id:3,name:"Class F fly ash",category:"Minerals",quantity:"70 tonnes",location:"Nagpur, MH",price:"₹1,100 / t",carbon:"18.9 t CO₂e",owner:"Vardhan Energy",condition:"Lab tested",color:"ash",icon:"Si",applications:["Low-carbon concrete", "Bricks & blocks", "Cement replacement"]},
 {id:4,name:"Reclaimed teak beams",category:"Wood",quantity:"3.2 tonnes",location:"Bengaluru, KA",price:"₹92,000 / t",carbon:"7.7 t CO₂e",owner:"Second Grain Co.",condition:"De-nailed",color:"wood",icon:"W",applications:["Interior joinery", "Furniture", "Architectural finishes"]},
 {id:5,name:"HDPE regrind",category:"Plastics",quantity:"12 tonnes",location:"Chennai, TN",price:"₹64,000 / t",carbon:"21.6 t CO₂e",owner:"Loop Polymers",condition:"Washed flakes",color:"plastic",icon:"HD",applications:["Injection moulding", "Pipes", "Non-food packaging"]},
 {id:6,name:"Copper cable offcuts",category:"Metals",quantity:"1.8 tonnes",location:"Hyderabad, TS",price:"₹590,000 / t",carbon:"11.3 t CO₂e",owner:"Volt Renew",condition:"99.5% purity",color:"copper",icon:"Cu",applications:["Wire rod", "Electrical components", "Alloy feedstock"]},
 {id:7,name:"Clear cullet glass",category:"Glass",quantity:"15 tonnes",location:"Mumbai, MH",price:"₹5,200 / t",carbon:"4.8 t CO₂e",owner:"GlassLoop India",condition:"Sorted",color:"glass",icon:"G",applications:["New containers", "Tiles", "Insulation"]},
 {id:8,name:"Cotton textile offcuts",category:"Textiles",quantity:"2.4 tonnes",location:"Tiruppur, TN",price:"₹38,000 / t",carbon:"9.6 t CO₂e",owner:"Mend Textile Lab",condition:"Pre-consumer",color:"textile",icon:"CT",applications:["Acoustic panels", "Recycled yarn", "Padding"]},
]
const trends=[{m:"Mar",v:21},{m:"Apr",v:30},{m:"May",v:25},{m:"Jun",v:43},{m:"Jul",v:48},{m:"Aug",v:61}]
const categories=[{name:"Metals",value:126},{name:"Plastics",value:54},{name:"Minerals",value:41},{name:"Wood",value:29}]

export default function Page(){
 const [view,setView]=useState<"home"|"market"|"details"|"dashboard"|"list"|"classifier">("home"), [selected,setSelected]=useState<Material>(materials[0]), [query,setQuery]=useState(""), [category,setCategory]=useState("All"), [location,setLocation]=useState("All locations"), [sort,setSort]=useState("recent"), [liked,setLiked]=useState<number[]>([]), [requested,setRequested]=useState(false), [showAuth,setShowAuth]=useState(false), [classified,setClassified]=useState(false), [isClassifying,setIsClassifying]=useState(false), [calc,setCalc]=useState({type:"Steel",qty:10,distance:50})
 const filtered=useMemo(()=>materials.filter(m=>(category==="All"||m.category===category)&&(location==="All locations"||m.location.includes(location))&&`${m.name} ${m.location} ${m.category}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==="carbon"?parseFloat(b.carbon)-parseFloat(a.carbon):sort==="value"?parseInt(b.price.replace(/\D/g,""))-parseInt(a.price.replace(/\D/g,"")):a.id-b.id),[category,location,query,sort])
 const nav=(to:typeof view)=>{setView(to); window.scrollTo({top:0,behavior:"smooth"})}
 const openMaterial=(m:Material)=>{setSelected(m); setRequested(false);nav("details")}
 const request=()=>{setRequested(true);toast.success("Request submitted",{description:`${selected.owner} will receive your request for ${selected.name}.`})}
 const handleList=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();toast.success("Material listing saved",{description:"It is now pending verification."});e.currentTarget.reset()}
 const runClassification=()=>{setIsClassifying(true);window.setTimeout(()=>{setIsClassifying(false);setClassified(true);toast.success("Demo analysis complete",{description:"HDPE plastic identified with 92% confidence."})},700)}
 const estimate=Math.round(calc.qty*({Steel:1.6,Aluminium:8.8,Plastic:1.8,Wood:0.7}[calc.type]||1.2)*(1-Math.min(calc.distance/1000,.25)))
 return <main>
  <Toaster richColors position="top-right" />
  <header className="nav"><button className="brand" onClick={()=>nav("home")}><span className="brand-mark"><Leaf size={19}/></span>CIRCULA</button><nav><button onClick={()=>nav("market")}>Marketplace</button><button onClick={()=>nav("classifier")}>AI Classifier</button><button onClick={()=>nav("dashboard")}>Impact</button></nav><div className="nav-actions"><button className="text-button" onClick={()=>setShowAuth(true)}>Sign in</button><button className="button small" onClick={()=>nav("list")}>List material <ArrowRight size={15}/></button></div></header>
  {view==="home"&&<><section className="hero"><div className="hero-copy"><p className="eyebrow"><Sparkles size={14}/> THE INDUSTRIAL CIRCULAR NETWORK</p><h1>Waste is a resource<br/><em>waiting for a match.</em></h1><p className="lead">Circula helps organizations exchange valuable industrial materials, verify their journey, and measure every tonne of impact.</p><div className="hero-actions"><button className="button" onClick={()=>nav("market")}>Explore materials <ArrowRight size={17}/></button><button className="button ghost" onClick={()=>nav("list")}>List your material</button></div><div className="trust"><BadgeCheck size={17}/><span>Verified organizations</span><i></i><ShieldCheck size={17}/><span>Traceable records</span></div></div><div className="hero-visual"><div className="orb orb-one"></div><div className="orb orb-two"></div><div className="material-stack"><div className="visual-card top"><span>Material flow</span><strong>12,480 <small>tonnes recirculated</small></strong><div className="mini-bars"><b></b><b></b><b></b><b></b><b></b><b></b></div></div><div className="visual-card bottom"><span className="round-icon"><Leaf size={21}/></span><p>Carbon avoided</p><strong>2,847 <small>t CO₂e</small></strong><span className="up">↑ 18.6% this month</span></div><div className="orbit-text">CIRCULAR • TRACEABLE • MEASURABLE • </div></div></div></section><section className="numbers"><div><strong>12.4K</strong><span>tonnes diverted</span></div><div><strong>2,847</strong><span>tCO₂e avoided</span></div><div><strong>186</strong><span>active organizations</span></div><div><strong>94%</strong><span>materials reused</span></div></section><section className="section how"><p className="eyebrow dark"><Zap size={14}/> BUILT FOR REAL CIRCULARITY</p><h2>One platform. A complete<br/>resource journey.</h2><div className="steps"><article><span>01</span><PackageOpen/><h3>List surplus</h3><p>Turn industrial by-products into discoverable, verified resources.</p></article><article><span>02</span><Sparkles/><h3>Match with purpose</h3><p>AI-assisted classification makes valuable reuse pathways visible.</p></article><article><span>03</span><ShieldCheck/><h3>Track the impact</h3><p>Immutable-ready ownership and carbon records that tell the full story.</p></article></div></section><section className="cta-band"><div><p className="eyebrow"><Leaf size={14}/> READY TO RECIRCULATE?</p><h2>Give materials their<br/><em>next useful life.</em></h2></div><button className="button light" onClick={()=>nav("market")}>Browse marketplace <ArrowRight size={17}/></button></section></>}
  {view==="market"&&<section className="page"><div className="page-heading"><p className="eyebrow dark">MARKETPLACE / LIVE INVENTORY</p><h1>Find value in what’s left behind.</h1><p>Verified industrial resources ready for their next use.</p></div><div className="filters"><label><Search size={18}/><input aria-label="Search materials" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search materials, categories or locations"/></label><select aria-label="Filter by category" value={category} onChange={e=>setCategory(e.target.value)}>{["All","Metals","Minerals","Wood","Plastics","Glass","Textiles"].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Filter by location" value={location} onChange={e=>setLocation(e.target.value)}><option>All locations</option><option>Pune</option><option>Ahmedabad</option><option>Nagpur</option><option>Bengaluru</option><option>Chennai</option><option>Hyderabad</option><option>Mumbai</option><option>Tiruppur</option></select></div><div className="list-meta"><span aria-live="polite">{filtered.length} materials available</span><label className="sort-label">Sort <select aria-label="Sort materials" value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">Most recent</option><option value="carbon">Carbon impact</option><option value="value">Highest value</option></select></label></div><div className="grid">{filtered.map(m=><article className="material-card" key={m.id}><div className={`material-image ${m.color}`}><span>{m.icon}</span><button aria-label={liked.includes(m.id)?`Remove ${m.name} from favourites`:`Add ${m.name} to favourites`} onClick={()=>setLiked(x=>x.includes(m.id)?x.filter(i=>i!==m.id):[...x,m.id])}><Heart size={18} fill={liked.includes(m.id)?"currentColor":"none"}/></button><small><BadgeCheck size={13}/> VERIFIED</small></div><div className="card-content"><p>{m.category} <i>•</i> {m.condition}</p><h3>{m.name}</h3><div className="card-row"><span><Boxes size={15}/>{m.quantity}</span><span><MapPin size={15}/>{m.location}</span></div><div className="card-footer"><div><strong>{m.price}</strong><small><Leaf size={13}/> {m.carbon} avoided</small></div><button className="circle-button" aria-label={`View details for ${m.name}`} onClick={()=>openMaterial(m)}><ChevronRight size={19}/></button></div></div></article>)}</div>{!filtered.length&&<div className="empty" role="status"><PackageOpen size={32}/><h3>No materials found</h3><p>Try adjusting your search or category filter.</p><button className="text-button" onClick={()=>{setQuery("");setCategory("All");setLocation("All locations")}}>Clear filters</button></div>}</section>}
  {view==="details"&&<section className="page details"><button className="back" onClick={()=>nav("market")}>← Back to marketplace</button><div className="detail-grid"><div><div className={`detail-image material-image ${selected.color}`}><span>{selected.icon}</span><small><BadgeCheck size={13}/> VERIFIED MATERIAL</small></div><div className="detail-section"><p className="eyebrow dark">OWNERSHIP / TRACEABLE RECORD</p><h2>Ownership timeline</h2><div className="timeline"><div><b><Check size={14}/></b><p><strong>Listed by {selected.owner}</strong><span>18 Aug 2026 · Verification complete</span></p></div><div><b><Check size={14}/></b><p><strong>Material classification recorded</strong><span>Ref: 0x8e9d...4c71 · AI-assisted review</span></p></div><div><b><Check size={14}/></b><p><strong>Available for exchange</strong><span>Current owner: {selected.owner}</span></p></div></div><p className="ledger-note"><ShieldCheck size={16}/> Simulated immutable ledger record · Blockchain-ready integration</p></div></div><div className="detail-info"><p className="eyebrow dark">{selected.category} / VERIFIED</p><h1>{selected.name}</h1><p className="seller"><span>{selected.owner.slice(0,1)}</span> Listed by <strong>{selected.owner}</strong><BadgeCheck size={16}/></p><div className="detail-stats"><div><span>Quantity</span><strong>{selected.quantity}</strong></div><div><span>Condition</span><strong>{selected.condition}</strong></div><div><span>Location</span><strong>{selected.location}</strong></div><div><span>Value</span><strong>{selected.price}</strong></div></div><div className="impact-box"><Leaf size={23}/><div><span>Estimated carbon saving</span><strong>{selected.carbon}</strong><p>vs. conventional virgin production</p></div></div><div className="actions">{requested?<div className="request-confirm"><Check/> Request sent — {selected.owner} will respond shortly.</div>:<button className="button full" onClick={request}>Request this material <Send size={16}/></button>}<button className="button ghost full" onClick={()=>toast.success("Saved to your shortlist")}>Save to wishlist <Heart size={16}/></button></div><div className="detail-section"><h3>Suggested reuse applications</h3>{selected.applications.map(a=><span className="tag" key={a}>{a}</span>)}</div></div></div></section>}
  {view==="classifier"&&<section className="page classifier"><div className="page-heading"><p className="eyebrow dark"><Sparkles size={14}/> AI-ASSISTED CLASSIFICATION</p><h1>Know the potential<br/>inside every material.</h1><p>Use this demo assistant to explore likely material categories and reuse pathways.</p></div><div className="classifier-grid"><div className="upload-box"><CloudUpload size={34}/><h3>Drop a material image here</h3><p>PNG, JPG or WEBP · max 10MB</p><label className="button ghost">Choose file<input type="file" hidden accept="image/*" onChange={()=>toast.info("Image selected",{description:"Run the demo analysis to see the sample result."})}/></label><span>or describe the material</span><textarea aria-label="Describe a material for classification" placeholder="e.g. blue industrial plastic flakes..."/></div><div className="classification-result"><div className="result-label"><span>DEMO MODE</span> Mock model output — ready to connect to a vision API.</div>{!classified?<div className="run-state" aria-live="polite"><Sparkles className={isClassifying?"analysis-pulse":""} size={32}/><h3>{isClassifying?"Analysing material…":"Ready to analyse"}</h3><p>{isClassifying?"Evaluating material attributes and reuse pathways.":"Choose a file or description, then run the demo classifier."}</p><button className="button" disabled={isClassifying} onClick={runClassification}>{isClassifying?"Analysing…":"Run demo analysis"} <ArrowRight size={16}/></button></div>:<div className="result"><div className="confidence"><span>92%</span><small>confidence</small></div><p>Predicted material</p><h2>HDPE Plastic</h2><span className="tag">Polymer / recyclable</span><h3>Recommended pathways</h3><ul><li>Mechanical recycling into regrind</li><li>Non-food packaging or pipe manufacture</li><li>Closed-loop collection partner matching</li></ul><div className="impact-box small-impact"><Leaf size={20}/><div><span>Estimated potential saving</span><strong>1.8 t CO₂e / tonne</strong></div></div><button className="text-button" onClick={()=>setClassified(false)}>Analyse another material</button></div>}</div></div></section>}
  {view==="dashboard"&&<section className="page dashboard"><div className="page-heading compact"><p className="eyebrow dark">NEXCYCLE WORKS / ORGANIZATION IMPACT</p><h1>Impact, made visible.</h1><p>Performance across your materials network · estimates based on exchange records.</p></div><div className="kpis"><div><span><PackageOpen/></span><strong>148.2 t</strong><p>Waste diverted</p><small>↑ 16% vs. last month</small></div><div><span><Leaf/></span><strong>312.8 t</strong><p>CO₂e avoided</p><small>↑ 21% vs. last month</small></div><div><span><CircleDollarSign/></span><strong>₹18.6L</strong><p>Value recaptured</p><small>Across 24 exchanges</small></div><div><span><Boxes/></span><strong>94%</strong><p>Reuse rate</p><small>+4.2% vs. target</small></div></div><div className="charts"><article><div className="chart-title"><div><h3>Carbon avoided over time</h3><p>tonnes CO₂e · estimated</p></div><span className="trend">↑ 18.6%</span></div><ResponsiveContainer width="100%" height={260}><AreaChart data={trends}><defs><linearGradient id="green" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#3bd17d" stopOpacity=".4"/><stop offset="1" stopColor="#3bd17d" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e8edea"/><XAxis dataKey="m" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip/><Area dataKey="v" stroke="#178a4d" strokeWidth={3} fill="url(#green)"/></AreaChart></ResponsiveContainer></article><article><div className="chart-title"><div><h3>Impact by material</h3><p>tonnes CO₂e avoided</p></div></div><ResponsiveContainer width="100%" height={260}><BarChart data={categories}><CartesianGrid vertical={false} stroke="#e8edea"/><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="value" fill="#b8e6c8" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></article></div><section className="calculator"><div><p className="eyebrow dark">CARBON IMPACT CALCULATOR</p><h2>Estimate your next exchange.</h2><p>These values are indicative lifecycle estimates, not verified emissions credits.</p></div><div className="calc-form"><label>Material<select value={calc.type} onChange={e=>setCalc({...calc,type:e.target.value})}>{["Steel","Aluminium","Plastic","Wood"].map(x=><option key={x}>{x}</option>)}</select></label><label>Quantity (tonnes)<input type="number" min="1" value={calc.qty} onChange={e=>setCalc({...calc,qty:+e.target.value})}/></label><label>Reuse distance (km)<input type="number" min="0" value={calc.distance} onChange={e=>setCalc({...calc,distance:+e.target.value})}/></label><div className="calc-result"><span>ESTIMATED AVOIDED</span><strong>{estimate} t <small>CO₂e</small></strong><p>{calc.qty} tonnes diverted from disposal</p></div></div></section></section>}
  {view==="list"&&<section className="page list-page"><div className="form-intro"><p className="eyebrow dark">NEW MATERIAL LISTING</p><h1>Put surplus to<br/><em>better use.</em></h1><p>Complete the details below. Your listing will be reviewed before it appears on the marketplace.</p><div className="form-aside"><ShieldCheck/><div><strong>Verification-led marketplace</strong><p>Every material is reviewed for clearer, more trusted exchanges.</p></div></div></div><form className="listing-form" onSubmit={handleList}><label>Material name<input required placeholder="e.g. Recycled steel billets"/></label><div className="two"><label>Category<select required><option value="">Select category</option><option>Metals</option><option>Plastics</option><option>Wood</option><option>Minerals</option></select></label><label>Condition<select required><option value="">Select condition</option><option>Clean / sorted</option><option>As generated</option><option>Refurbished</option></select></label></div><label>Description<textarea required placeholder="Describe composition, grade, and any relevant handling details."/></label><div className="two"><label>Quantity<input required type="number" min="1" placeholder="0"/></label><label>Unit<select><option>tonnes</option><option>kg</option><option>units</option></select></label></div><div className="two"><label>Location<input required placeholder="City, State"/></label><label>Expected value<input placeholder="₹ per unit"/></label></div><label className="upload-field"><CloudUpload size={18}/> Add material images <input type="file" hidden accept="image/*" onChange={()=>toast.info("Image added to draft")}/></label><button className="button full" type="submit">Submit for verification <ArrowRight size={16}/></button></form></section>}
  {showAuth&&<div className="modal-wrap" role="dialog" aria-modal="true" aria-labelledby="sign-in-title"><div className="modal"><button className="modal-close" aria-label="Close sign-in dialog" onClick={()=>setShowAuth(false)}><X/></button><span className="brand-mark"><Leaf size={20}/></span><h2 id="sign-in-title">Welcome to Circula</h2><p>Sign in to manage your exchanges and impact.</p><form className="auth-form" onSubmit={e=>{e.preventDefault();setShowAuth(false);toast.success("Demo sign-in complete")}}><label>Email<input required type="email" placeholder="you@organization.com"/></label><label>Password<input required type="password" minLength={8} placeholder="••••••••"/></label><button className="forgot-password" type="button" onClick={()=>toast.info("Password reset link requested",{description:"Demo only: connect your email provider to send a real reset link."})}>Forgot password?</button><button className="button full" type="submit">Sign in</button><button className="text-button auth-signup" type="button" onClick={()=>toast.info("Demo sign-up ready",{description:"Connect an authentication provider to create production accounts."})}>New to Circula? Create an organization account</button></form><small>Demo authentication interface — connect your identity provider here.</small></div></div>}
 </main>
}
